// Conteúdo da colinha. Cada dica descreve uma situação, os comandos e uma explicação.
// Campos opcionais: warning (comandos destrutivos), legacy (comando antigo equivalente),
// keywords (termos extras para a busca) e file (quando o código é conteúdo de arquivo, não terminal).

export const CATEGORIES = [
  { id: 'primeiros-passos', label: 'Primeiros passos', icon: '🚀' },
  { id: 'dia-a-dia', label: 'Dia a dia', icon: '📝' },
  { id: 'branches', label: 'Branches', icon: '🌿' },
  { id: 'remotos', label: 'Remotos e GitHub', icon: '☁️' },
  { id: 'desfazendo', label: 'Desfazendo coisas', icon: '↩️' },
  { id: 'historico', label: 'Histórico e investigação', icon: '🔎' },
  { id: 'stash', label: 'Stash', icon: '📦' },
  { id: 'tags', label: 'Tags e releases', icon: '🏷️' },
  { id: 'conflitos', label: 'Conflitos', icon: '⚔️' },
  { id: 'gitignore', label: '.gitignore', icon: '🙈' },
  { id: 'socorro', label: 'Socorro!', icon: '🆘' },
];

export const ENTRIES = [
  // Primeiros passos
  {
    id: 'configurar-nome-email',
    category: 'primeiros-passos',
    title: 'Configurar seu nome e e-mail',
    commands: ['git config --global user.name "Maria Exemplo"', 'git config --global user.email "maria@example.com"'],
    explanation: 'Todo commit registra o nome e o e-mail de quem o fez. Com `--global`, a configuração vale para todos os repositórios do seu usuário; sem `--global`, rodando dentro de um repositório, vale só para ele. Use o mesmo e-mail da sua conta no GitHub para os commits aparecerem no seu perfil.',
    keywords: ['identidade', 'autor', 'usuário'],
  },
  {
    id: 'branch-inicial-main',
    category: 'primeiros-passos',
    title: 'Fazer os repositórios novos começarem na branch main',
    commands: ['git config --global init.defaultBranch main'],
    explanation: 'Define o nome da branch criada pelo `git init` (opção disponível desde o Git 2.28). O GitHub já usa `main` como padrão nos repositórios criados por lá.',
    keywords: ['master', 'padrão'],
  },
  {
    id: 'editor-padrao',
    category: 'primeiros-passos',
    title: 'Escolher o editor das mensagens de commit',
    commands: ['git config --global core.editor "code --wait"', 'git config --global core.editor nano'],
    explanation: 'O Git abre esse editor quando você roda `git commit` sem `-m`, no rebase interativo e em outros momentos. Com o VS Code, o `--wait` faz o Git esperar você fechar a aba antes de continuar.',
    keywords: ['vscode', 'vim', 'nano'],
  },
  {
    id: 'ver-configuracoes',
    category: 'primeiros-passos',
    title: 'Ver suas configurações e de onde elas vêm',
    commands: ['git config --list --show-origin', 'git config user.email'],
    explanation: 'O primeiro comando lista todas as configurações e mostra em qual arquivo cada uma foi definida (do sistema, global ou do repositório). O segundo mostra um único valor: o que vale no repositório atual.',
  },
  {
    id: 'fim-de-linha',
    category: 'primeiros-passos',
    title: 'Evitar confusão de fim de linha entre Windows, macOS e Linux',
    commands: ['git config --global core.autocrlf true', 'git config --global core.autocrlf input'],
    explanation: 'Use `true` no Windows (o Git converte LF em CRLF ao trazer os arquivos e de volta para LF ao commitar) e `input` no macOS e no Linux (converte CRLF em LF ao commitar). Em equipe, um arquivo `.gitattributes` com a linha `* text=auto` deixa a regra registrada no próprio repositório.',
    keywords: ['crlf', 'lf', 'quebra de linha', 'line ending'],
  },
  {
    id: 'iniciar-repositorio',
    category: 'primeiros-passos',
    title: 'Transformar uma pasta em repositório Git',
    commands: ['git init', 'git init meu-projeto'],
    explanation: 'O `git init` cria a pasta oculta `.git` no diretório atual; é nela que fica todo o histórico. Passando um nome, o Git cria a pasta e o repositório dentro dela. Nada é versionado até você fazer `git add` e `git commit`.',
    keywords: ['criar repositório', 'novo projeto'],
  },
  {
    id: 'primeiro-commit',
    category: 'primeiros-passos',
    title: 'Do zero ao primeiro commit',
    commands: ['git init', 'git add .', 'git commit -m "Primeiro commit"'],
    explanation: 'O fluxo básico: crie o repositório, prepare os arquivos (staging) e registre o commit. Antes disso, configure seu nome e e-mail e crie um `.gitignore` para não versionar o que não deve, como `node_modules/` ou `.env`.',
  },
  {
    id: 'clonar',
    category: 'primeiros-passos',
    title: 'Baixar (clonar) um repositório existente',
    commands: ['git clone https://github.com/usuario/projeto.git', 'git clone https://github.com/usuario/projeto.git outra-pasta'],
    explanation: 'Copia o repositório inteiro, com todo o histórico, e já configura o remoto `origin` apontando para a URL. A pasta recebe o nome do projeto; passe um segundo argumento para escolher outro nome.',
    keywords: ['download', 'copiar'],
  },
  {
    id: 'clone-raso',
    category: 'primeiros-passos',
    title: 'Clonar rápido, só com o histórico recente',
    commands: ['git clone --depth 1 <url>', 'git fetch --unshallow'],
    explanation: 'O clone raso traz só o último commit da branch principal: ótimo para repositórios enormes ou quando você só quer usar o código. Se depois precisar do histórico completo, rode `git fetch --unshallow` dentro do repositório.',
    keywords: ['shallow', 'depth'],
  },
  {
    id: 'aliases',
    category: 'primeiros-passos',
    title: 'Criar atalhos para os comandos que você mais usa',
    commands: ['git config --global alias.st status', 'git config --global alias.lg "log --oneline --graph --all"'],
    explanation: 'Depois disso, `git st` vira `git status` e `git lg` mostra o histórico em forma de gráfico. Os atalhos ficam salvos no arquivo `~/.gitconfig`.',
    keywords: ['alias', 'atalho'],
  },

  // Dia a dia
  {
    id: 'status',
    category: 'dia-a-dia',
    title: 'Ver o que mudou desde o último commit',
    commands: ['git status', 'git status -s'],
    explanation: 'Mostra a branch atual, os arquivos modificados, os que já estão preparados para o commit (staging) e os que o Git ainda não rastreia. Com `-s`, a saída fica compacta: `M` = modificado, `A` = adicionado, `??` = não rastreado.',
  },
  {
    id: 'adicionar-arquivos',
    category: 'dia-a-dia',
    title: 'Preparar arquivos para o commit (git add)',
    commands: ['git add <arquivo>', 'git add .', 'git add -A'],
    explanation: 'O `git add` coloca as alterações na área de preparação (staging), que é o que vai entrar no próximo commit. O `git add .` pega tudo a partir da pasta atual, incluindo arquivos novos e apagados; o `git add -A` pega tudo do repositório, não importa em que pasta você esteja.',
    keywords: ['stage', 'staging', 'index', 'adicionar'],
  },
  {
    id: 'adicionar-trechos',
    category: 'dia-a-dia',
    title: 'Adicionar só alguns trechos de um arquivo',
    commands: ['git add -p <arquivo>'],
    explanation: 'O Git mostra cada bloco de alteração e pergunta o que fazer: `y` adiciona, `n` pula, `s` divide o bloco em partes menores, `q` sai e `?` mostra todas as opções. Ótimo para separar alterações sem relação em commits diferentes.',
    keywords: ['patch', 'hunk', 'parcial'],
  },
  {
    id: 'commit',
    category: 'dia-a-dia',
    title: 'Registrar um commit',
    commands: ['git commit -m "Adiciona validação de CPF no cadastro"', 'git commit'],
    explanation: 'Grava o que está no staging como um novo commit. Sem `-m`, o Git abre o editor para você escrever a mensagem. Uma boa mensagem resume em uma linha curta o que o commit faz; os detalhes vão em parágrafos abaixo, depois de uma linha em branco.',
  },
  {
    id: 'commit-tudo',
    category: 'dia-a-dia',
    title: 'Commitar de uma vez tudo o que já é rastreado',
    commands: ['git commit -am "Corrige cálculo do frete"'],
    explanation: 'O `-a` inclui automaticamente os arquivos modificados ou apagados que o Git já rastreia. Arquivos novos (não rastreados) ficam de fora: para eles, use `git add` antes.',
  },
  {
    id: 'diff',
    category: 'dia-a-dia',
    title: 'Ver as alterações que ainda não foram preparadas',
    commands: ['git diff', 'git diff <arquivo>'],
    explanation: 'Compara seus arquivos com a área de preparação: mostra o que você mudou e ainda não passou pelo `git add`. Linhas com `+` foram adicionadas; com `-`, removidas. Para ver só a lista de arquivos, use `git diff --stat`.',
    keywords: ['diferença', 'mudanças'],
  },
  {
    id: 'diff-staged',
    category: 'dia-a-dia',
    title: 'Ver o que vai entrar no próximo commit',
    commands: ['git diff --staged'],
    explanation: 'Mostra a diferença entre o último commit e a área de preparação, ou seja, exatamente o que o próximo `git commit` vai gravar. O `--cached` é um sinônimo.',
  },
  {
    id: 'diff-branches',
    category: 'dia-a-dia',
    title: 'Comparar duas branches',
    commands: ['git diff main <branch>', 'git diff main...<branch>', 'git diff --stat main...<branch>'],
    explanation: 'O primeiro compara as pontas das duas branches. Com três pontos, o Git mostra só o que mudou em `<branch>` desde que ela saiu da `main`, que é o que um pull request exibe. O `--stat` resume em arquivos e quantidade de linhas.',
    keywords: ['comparar'],
  },
  {
    id: 'log-basico',
    category: 'dia-a-dia',
    title: 'Ver o histórico de commits',
    commands: ['git log', 'git log --oneline', 'git log -5'],
    explanation: 'Lista os commits do mais recente para o mais antigo, com autor, data e mensagem. O `--oneline` mostra um commit por linha (hash curto e título) e o `-5` limita aos cinco últimos. Aperte `q` para sair.',
    keywords: ['histórico', 'history'],
  },
  {
    id: 'remover-arquivo',
    category: 'dia-a-dia',
    title: 'Apagar um arquivo do projeto',
    commands: ['git rm <arquivo>', 'git rm -r <pasta>'],
    explanation: 'Apaga o arquivo do disco e já registra a remoção no staging; falta só o commit. Se você apagou o arquivo por fora do Git, `git add <arquivo>` (ou `git add -A`) registra a remoção do mesmo jeito.',
    keywords: ['deletar', 'excluir'],
  },
  {
    id: 'renomear-arquivo',
    category: 'dia-a-dia',
    title: 'Renomear ou mover um arquivo',
    commands: ['git mv nome-antigo.js nome-novo.js'],
    explanation: 'Renomeia o arquivo e registra a mudança no staging. O Git reconhece renomeações pelo conteúdo, então renomear pelo sistema e rodar `git add -A` depois dá no mesmo.',
    keywords: ['rename', 'mover'],
  },

  // Branches
  {
    id: 'listar-branches',
    category: 'branches',
    title: 'Listar as branches',
    commands: ['git branch', 'git branch -a', 'git branch -vv'],
    explanation: 'Sem opções, lista as branches locais e marca a atual com `*`. O `-a` inclui as branches remotas (como `origin/main`); o `-vv` mostra o último commit de cada uma e qual branch remota ela acompanha.',
  },
  {
    id: 'criar-branch',
    category: 'branches',
    title: 'Criar uma branch nova e ir para ela',
    commands: ['git switch -c <nova-branch>'],
    legacy: 'git checkout -b <nova-branch>',
    explanation: 'Cria a branch a partir do commit atual e já muda para ela. O `git switch` existe desde o Git 2.23 e é mais claro que o antigo `git checkout`, que faz coisas demais. Para só criar, sem trocar de branch, use `git branch <nova-branch>`.',
    keywords: ['nova branch', 'create'],
  },
  {
    id: 'trocar-branch',
    category: 'branches',
    title: 'Trocar de branch',
    commands: ['git switch <branch>', 'git switch -'],
    legacy: 'git checkout <branch>',
    explanation: 'Muda para outra branch e atualiza seus arquivos. O `git switch -` volta para a branch anterior, como o `cd -` do terminal. Se você tiver alterações que entrariam em conflito, o Git recusa a troca: faça um commit ou guarde-as com `git stash` antes.',
    keywords: ['mudar', 'alternar'],
  },
  {
    id: 'branch-de-commit-antigo',
    category: 'branches',
    title: 'Criar uma branch a partir de um commit antigo',
    commands: ['git switch -c <nova-branch> <hash>'],
    legacy: 'git checkout -b <nova-branch> <hash>',
    explanation: 'Útil para investigar uma versão antiga ou corrigir algo a partir de um ponto específico do histórico, sem afetar as outras branches. No lugar do hash, também vale o nome de uma tag ou de outra branch.',
  },
  {
    id: 'renomear-branch',
    category: 'branches',
    title: 'Renomear uma branch',
    commands: ['git branch -m <novo-nome>', 'git branch -m <nome-antigo> <novo-nome>'],
    explanation: 'O primeiro renomeia a branch atual; o segundo, qualquer branch local. Se ela já estava no GitHub, envie a nova com `git push -u origin <novo-nome>` e apague a antiga com `git push origin --delete <nome-antigo>`.',
    keywords: ['rename'],
  },
  {
    id: 'apagar-branch',
    category: 'branches',
    title: 'Apagar uma branch local',
    commands: ['git branch -d <branch>', 'git branch -D <branch>'],
    explanation: 'O `-d` só apaga se o trabalho da branch já foi incorporado (merge), para você não perder nada. O `-D` força a remoção mesmo assim.',
    warning: 'Com `-D`, commits que não estão em nenhuma outra branch deixam de aparecer. Se foi sem querer, dá para recuperar pelo `git reflog` (veja “Apaguei uma branch sem querer”).',
    keywords: ['deletar', 'excluir'],
  },
  {
    id: 'merge',
    category: 'branches',
    title: 'Juntar uma branch na atual (merge)',
    commands: ['git switch main', 'git merge <branch>'],
    explanation: 'Traz para a branch atual os commits da outra. Se a `main` não andou desde que a branch foi criada, o Git só avança o ponteiro (fast-forward); se as duas andaram, ele cria um commit de merge. Em caso de conflito, veja a seção Conflitos.',
    keywords: ['mesclar', 'integrar'],
  },
  {
    id: 'merge-no-ff',
    category: 'branches',
    title: 'Fazer merge sempre com commit de merge',
    commands: ['git merge --no-ff <branch>'],
    explanation: 'Mesmo quando daria para só avançar o ponteiro (fast-forward), o Git cria um commit de merge. Assim o histórico mostra claramente quais commits chegaram juntos.',
  },
  {
    id: 'merge-squash',
    category: 'branches',
    title: 'Juntar todos os commits de uma branch em um só',
    commands: ['git merge --squash <branch>', 'git commit -m "Adiciona busca de produtos"'],
    explanation: 'O `--squash` aplica todas as alterações da branch de uma vez no staging, sem criar commit de merge; você faz um commit único em seguida. Como o Git não registra a ligação com a branch original, o `git branch -d` vai dizer que ela não foi incorporada: confira e use `-D`.',
    keywords: ['squash', 'um commit só'],
  },
  {
    id: 'rebase',
    category: 'branches',
    title: 'Atualizar sua branch com a main usando rebase',
    commands: ['git switch <branch>', 'git rebase main'],
    explanation: 'Reaplica os seus commits por cima da ponta da `main`, deixando o histórico linear, sem commit de merge. Os commits são recriados e ganham novos hashes.',
    warning: 'Não faça rebase de commits que outras pessoas já baixaram. Se a branch já estava no GitHub, você vai precisar de `git push --force-with-lease`; combine antes com quem também trabalha nela.',
  },
  {
    id: 'rebase-interativo',
    category: 'branches',
    title: 'Juntar, reordenar ou editar commits (rebase interativo)',
    commands: ['git rebase -i HEAD~3'],
    explanation: 'Abre no editor a lista dos 3 últimos commits. Troque `pick` por `reword` (mudar a mensagem), `edit` (alterar o commit), `squash` (juntar com o anterior, combinando as mensagens), `fixup` (juntar descartando a mensagem) ou `drop` (remover). Também dá para reordenar as linhas.',
    warning: 'Reescreve o histórico: use em commits que ainda não foram compartilhados ou combine com o time antes de enviar com `--force-with-lease`.',
    keywords: ['squash', 'fixup', 'reword', 'organizar commits'],
  },
  {
    id: 'cherry-pick',
    category: 'branches',
    title: 'Trazer um commit específico de outra branch',
    commands: ['git cherry-pick <hash>', 'git cherry-pick <hash1> <hash2>'],
    explanation: 'Aplica na branch atual as alterações do commit indicado, criando um commit novo (com outro hash). Útil para levar uma correção para outra branch sem fazer merge de tudo.',
    keywords: ['copiar commit'],
  },
  {
    id: 'branches-incorporadas',
    category: 'branches',
    title: 'Ver quais branches já foram incorporadas',
    commands: ['git branch --merged main', 'git branch --no-merged main'],
    explanation: 'O primeiro lista as branches cujos commits já estão todos na `main`, candidatas seguras a `git branch -d`. O segundo lista as que ainda têm trabalho pendente.',
    keywords: ['limpar branches', 'merged'],
  },

  // Remotos e GitHub
  {
    id: 'remoto-url',
    category: 'remotos',
    title: 'Ver ou trocar a URL do remoto',
    commands: ['git remote -v', 'git remote set-url origin git@github.com:usuario/projeto.git'],
    explanation: 'O primeiro lista os remotos (normalmente só o `origin`) com as URLs. O segundo troca a URL: por exemplo, de HTTPS para SSH, ou quando o repositório muda de nome ou de dono no GitHub.',
    keywords: ['origin', 'ssh', 'https'],
  },
  {
    id: 'conectar-github',
    category: 'remotos',
    title: 'Enviar um projeto local para um repositório novo no GitHub',
    commands: ['git remote add origin https://github.com/usuario/projeto.git', 'git branch -M main', 'git push -u origin main'],
    explanation: 'Crie o repositório vazio no GitHub (sem README, para não haver conflito) e rode esses comandos. O `git branch -M main` garante que sua branch se chama `main`; o `-u` liga a branch local à remota, para que os próximos `git push` e `git pull` funcionem sem argumentos.',
    keywords: ['publicar', 'subir projeto', 'remote add'],
  },
  {
    id: 'fetch',
    category: 'remotos',
    title: 'Buscar novidades do remoto sem mexer nos seus arquivos',
    commands: ['git fetch', 'git fetch --prune'],
    explanation: 'Baixa os commits e branches novos e atualiza as referências como `origin/main`, sem alterar suas branches nem seus arquivos. O `--prune` também remove as referências de branches que foram apagadas no remoto. Para ver o que chegou: `git log main..origin/main`.',
    keywords: ['atualizar', 'baixar'],
  },
  {
    id: 'pull',
    category: 'remotos',
    title: 'Baixar e integrar as novidades (pull)',
    commands: ['git pull'],
    explanation: 'É um `git fetch` seguido de um merge (ou de um rebase, conforme a sua configuração) da branch remota na branch atual. Faça antes de começar a trabalhar e antes de enviar, para reduzir conflitos.',
    keywords: ['atualizar', 'baixar'],
  },
  {
    id: 'pull-rebase',
    category: 'remotos',
    title: 'Fazer pull mantendo o histórico linear',
    commands: ['git pull --rebase', 'git config --global pull.rebase true'],
    explanation: 'Em vez de criar um commit de merge, o Git reaplica seus commits locais por cima do que veio do remoto. A configuração torna isso o padrão. Se o Git avisar sobre branches divergentes (“divergent branches”), é ele pedindo que você escolha: `pull.rebase true` (rebase) ou `pull.rebase false` (merge).',
  },
  {
    id: 'push',
    category: 'remotos',
    title: 'Enviar seus commits para o remoto',
    commands: ['git push', 'git push -u origin <branch>'],
    explanation: 'Envia os commits da branch atual. Na primeira vez que você envia uma branch nova, use `-u` (o mesmo que `--set-upstream`) para ligá-la à branch remota; depois, basta `git push`.',
    keywords: ['enviar', 'subir'],
  },
  {
    id: 'definir-upstream',
    category: 'remotos',
    title: 'Ligar uma branch local a uma branch remota (upstream)',
    commands: ['git branch -u origin/<branch>', 'git branch -vv'],
    explanation: 'Define qual branch remota a branch atual acompanha, para que `git pull`, `git push` e `git status` saibam com quem comparar. O `git branch -vv` mostra essas ligações e quantos commits você está à frente ou atrás.',
    keywords: ['tracking', 'set-upstream-to'],
  },
  {
    id: 'push-force-with-lease',
    category: 'remotos',
    title: 'Enviar depois de reescrever o histórico (amend, rebase)',
    commands: ['git push --force-with-lease'],
    explanation: 'Depois de um `commit --amend` ou de um rebase em commits já enviados, o push normal é rejeitado. O `--force-with-lease` sobrescreve a branch remota, mas só se ela ainda estiver como você a viu no último fetch: se alguém enviou commits nesse meio-tempo, o envio é recusado e nada se perde.',
    warning: 'Evite `git push --force`: ele sobrescreve sem conferir e pode apagar o trabalho de outras pessoas. Nunca reescreva o histórico da `main` compartilhada sem combinar com o time.',
    keywords: ['force push', 'forçar'],
  },
  {
    id: 'apagar-branch-remota',
    category: 'remotos',
    title: 'Apagar uma branch no GitHub',
    commands: ['git push origin --delete <branch>'],
    explanation: 'Remove a branch do remoto; a sua cópia local continua existindo. Os colegas podem limpar as referências antigas com `git fetch --prune`.',
    keywords: ['deletar', 'excluir'],
  },
  {
    id: 'branch-remota',
    category: 'remotos',
    title: 'Trabalhar numa branch que só existe no remoto',
    commands: ['git fetch', 'git switch <branch>'],
    legacy: 'git checkout <branch>',
    explanation: 'Se não existe uma branch local com esse nome, mas existe `origin/<branch>`, o `git switch` cria a branch local já ligada à remota.',
  },
  {
    id: 'ssh-github',
    category: 'remotos',
    title: 'Usar SSH com o GitHub',
    commands: ['ssh-keygen -t ed25519 -C "maria@example.com"', 'ssh -T git@github.com'],
    explanation: 'Gere a chave, cole o conteúdo do arquivo público (`~/.ssh/id_ed25519.pub`) em GitHub → Settings → SSH and GPG keys e teste a conexão com o segundo comando. Lembre-se: o GitHub não aceita a senha da conta em operações Git por HTTPS; use SSH ou um token de acesso pessoal.',
    keywords: ['chave', 'autenticação', 'login'],
  },
  {
    id: 'fork-atualizar',
    category: 'remotos',
    title: 'Manter seu fork atualizado com o projeto original',
    commands: [
      'git remote add upstream https://github.com/dono-original/projeto.git',
      'git fetch upstream',
      'git switch main',
      'git merge upstream/main',
      'git push origin main',
    ],
    explanation: 'Por convenção, `origin` é o seu fork e `upstream` é o repositório original. O remoto só precisa ser adicionado uma vez; depois, repita os outros comandos sempre que quiser sincronizar. No site do GitHub, o botão “Sync fork” faz o mesmo com a branch principal.',
    keywords: ['sincronizar', 'sync'],
  },
  {
    id: 'pull-request',
    category: 'remotos',
    title: 'Contribuir com um projeto via pull request',
    commands: [
      'git clone https://github.com/seu-usuario/projeto.git',
      'git switch -c corrige-erro-no-readme',
      'git commit -am "Corrige erro de digitação no README"',
      'git push -u origin corrige-erro-no-readme',
    ],
    explanation: 'Antes, faça um fork do projeto no GitHub e clone o seu fork. Trabalhe numa branch própria (não na `main`), envie essa branch e abra o pull request pelo GitHub, que mostra o botão “Compare & pull request” logo depois do push.',
    keywords: ['pr', 'contribuir', 'fork', 'open source'],
  },
  {
    id: 'testar-pr',
    category: 'remotos',
    title: 'Testar um pull request na sua máquina',
    commands: ['git fetch origin pull/123/head:pr-123', 'git switch pr-123'],
    explanation: 'O GitHub disponibiliza cada pull request como `pull/<número>/head`. O comando baixa o PR 123 para uma branch local chamada `pr-123`. Se você trabalha num fork, troque `origin` por `upstream`.',
    keywords: ['revisar', 'review', 'pr'],
  },

  // Desfazendo coisas
  {
    id: 'descartar-alteracoes',
    category: 'desfazendo',
    title: 'Descartar as alterações de um arquivo',
    commands: ['git restore <arquivo>', 'git restore .'],
    legacy: 'git checkout -- <arquivo>',
    explanation: 'Volta o arquivo para como ele está na área de preparação, ou no último commit se você não deu `git add`. O `git restore .` faz isso com todos os arquivos da pasta atual.',
    warning: 'As alterações descartadas não ficam guardadas em lugar nenhum: não há como recuperá-las.',
    keywords: ['jogar fora', 'voltar arquivo'],
  },
  {
    id: 'tirar-do-staging',
    category: 'desfazendo',
    title: 'Desfazer um git add (tirar do staging)',
    commands: ['git restore --staged <arquivo>'],
    legacy: 'git reset HEAD <arquivo>',
    explanation: 'Tira o arquivo da área de preparação, mas mantém as alterações nele. Útil quando você adicionou algo que não deveria entrar neste commit.',
    keywords: ['unstage', 'desfazer add'],
  },
  {
    id: 'reset-soft',
    category: 'desfazendo',
    title: 'Desfazer o último commit mantendo as alterações preparadas',
    commands: ['git reset --soft HEAD~1'],
    explanation: 'Remove o último commit, mas as alterações dele continuam no staging, prontas para um novo commit. `HEAD~1` é o commit anterior ao atual; use `HEAD~3` para voltar três.',
    keywords: ['uncommit'],
  },
  {
    id: 'reset-mixed',
    category: 'desfazendo',
    title: 'Desfazer o último commit mantendo as alterações nos arquivos',
    commands: ['git reset HEAD~1'],
    explanation: 'É o modo padrão (`--mixed`): remove o commit e tira as alterações do staging, mas elas continuam nos arquivos. Bom para reorganizar o trabalho em commits diferentes.',
    keywords: ['uncommit'],
  },
  {
    id: 'reset-hard',
    category: 'desfazendo',
    title: 'Jogar fora commits e alterações e voltar a um ponto',
    commands: ['git reset --hard HEAD~1', 'git reset --hard <hash>', 'git reset --hard origin/main'],
    explanation: 'Move a branch para o commit indicado e deixa staging e arquivos idênticos a ele. O último exemplo deixa sua branch igual à do remoto (rode `git fetch` antes).',
    warning: 'Destrutivo: alterações não commitadas são perdidas para sempre. Commits descartados ainda podem ser recuperados por um tempo com `git reflog`. Antes, considere um `git stash` ou uma branch de backup (`git branch backup`).',
    keywords: ['descartar tudo'],
  },
  {
    id: 'reset-modos',
    category: 'desfazendo',
    title: 'Entender a diferença entre --soft, --mixed e --hard',
    commands: ['git reset --soft <hash>', 'git reset --mixed <hash>', 'git reset --hard <hash>'],
    explanation: 'Os três movem a branch atual para `<hash>`. O `--soft` mantém staging e arquivos como estão; o `--mixed` (padrão) limpa o staging, mas mantém os arquivos; o `--hard` deixa staging e arquivos iguais ao commit, descartando tudo o que mudou depois.',
    warning: 'O `--hard` apaga alterações não commitadas sem volta.',
  },
  {
    id: 'revert',
    category: 'desfazendo',
    title: 'Desfazer um commit que já foi enviado',
    commands: ['git revert <hash>', 'git revert HEAD'],
    explanation: 'Cria um commit novo que faz o inverso do commit indicado, sem reescrever o histórico. É o jeito seguro de desfazer algo em branches compartilhadas, como a `main`.',
    keywords: ['desfazer push'],
  },
  {
    id: 'revert-merge',
    category: 'desfazendo',
    title: 'Desfazer um merge que já foi enviado',
    commands: ['git revert -m 1 <hash-do-merge>'],
    explanation: 'Um commit de merge tem dois “pais”; o `-m 1` diz para manter o lado da branch onde o merge foi feito (normalmente a `main`) e desfazer o que veio da outra branch.',
    warning: 'Se mais tarde você quiser fazer o merge daquela branch de novo, o Git vai considerar os commits antigos como já incorporados: antes, reverta o próprio commit de revert.',
  },
  {
    id: 'revert-varios',
    category: 'desfazendo',
    title: 'Desfazer vários commits seguidos sem reescrever o histórico',
    commands: ['git revert --no-commit HEAD~3..HEAD', 'git commit -m "Reverte as três últimas alterações"'],
    explanation: 'Reverte os três últimos commits de uma vez. Com `--no-commit`, as reversões ficam no staging e você grava tudo num único commit.',
  },
  {
    id: 'amend-mensagem',
    category: 'desfazendo',
    title: 'Corrigir a mensagem do último commit',
    commands: ['git commit --amend -m "Mensagem corrigida"'],
    explanation: 'Substitui o último commit por um novo, com a mensagem corrigida. Sem `-m`, o editor abre com a mensagem atual para você editar.',
    warning: 'O commit ganha outro hash. Se ele já foi enviado, você vai precisar de `git push --force-with-lease`; em branches compartilhadas, prefira deixar como está.',
    keywords: ['amend', 'editar mensagem'],
  },
  {
    id: 'amend-arquivo',
    category: 'desfazendo',
    title: 'Incluir um arquivo esquecido no último commit',
    commands: ['git add <arquivo>', 'git commit --amend --no-edit'],
    explanation: 'O `--no-edit` mantém a mensagem do commit. Vale o mesmo cuidado de qualquer `--amend`: só é tranquilo se o commit ainda não foi enviado.',
    keywords: ['amend', 'esqueci'],
  },
  {
    id: 'clean',
    category: 'desfazendo',
    title: 'Apagar arquivos não rastreados',
    commands: ['git clean -n', 'git clean -fd', 'git clean -i'],
    explanation: 'O `-n` só simula e lista o que seria apagado: rode sempre antes. O `-f` apaga de verdade e o `-d` inclui pastas; o `-i` pergunta item por item. Arquivos ignorados pelo `.gitignore` são preservados, a menos que você use `-x`.',
    warning: 'Arquivos não rastreados nunca passaram pelo Git: depois do `git clean -f`, não há como recuperá-los.',
    keywords: ['limpar', 'untracked'],
  },
  {
    id: 'restaurar-de-commit',
    category: 'desfazendo',
    title: 'Recuperar um arquivo como ele era em um commit antigo',
    commands: ['git restore --source=<hash> <arquivo>'],
    legacy: 'git checkout <hash> -- <arquivo>',
    explanation: 'Traz para a sua pasta de trabalho a versão do arquivo naquele commit, sem mudar de branch. Depois é só revisar e commitar. O comando antigo, além disso, já coloca o arquivo no staging.',
    warning: 'Substitui o conteúdo atual do arquivo: alterações não commitadas nele são perdidas.',
    keywords: ['versão antiga', 'voltar arquivo'],
  },
  {
    id: 'recuperar-arquivo-apagado',
    category: 'desfazendo',
    title: 'Recuperar um arquivo apagado em um commit antigo',
    commands: ['git log --oneline --diff-filter=D -- <arquivo>', 'git restore --source=<hash>~1 <arquivo>'],
    explanation: 'O primeiro comando mostra o commit que apagou o arquivo. Como o arquivo ainda existia no commit anterior a esse (`<hash>~1`), é de lá que você o restaura.',
    keywords: ['deletado', 'excluído', 'sumiu'],
  },

  // Histórico e investigação
  {
    id: 'log-grafico',
    category: 'historico',
    title: 'Ver o histórico como um gráfico de branches',
    commands: ['git log --oneline --graph --all'],
    explanation: 'Desenha no terminal as linhas das branches e dos merges, incluindo todas as branches (`--all`), com um commit por linha. Vale criar um atalho para ele (veja “Criar atalhos para os comandos que você mais usa”).',
    keywords: ['árvore', 'graph'],
  },
  {
    id: 'log-arquivo',
    category: 'historico',
    title: 'Ver o histórico de um arquivo',
    commands: ['git log --follow -p -- <arquivo>'],
    explanation: 'Lista os commits que mexeram no arquivo, com o diff de cada um (`-p`). O `--follow` continua acompanhando o arquivo mesmo depois de uma renomeação.',
  },
  {
    id: 'log-autor-data',
    category: 'historico',
    title: 'Filtrar commits por autor ou período',
    commands: ['git log --author="Maria"', 'git log --since="2026-01-01" --until="2026-03-31"'],
    explanation: 'O `--author` aceita parte do nome ou do e-mail. Os filtros podem ser combinados entre si e com um caminho, como em `git log --author="Maria" -- src/`.',
    keywords: ['data', 'quem'],
  },
  {
    id: 'log-mensagem',
    category: 'historico',
    title: 'Procurar commits pela mensagem',
    commands: ['git log --grep="login" -i'],
    explanation: 'Mostra os commits cuja mensagem contém o texto; o `-i` ignora a diferença entre maiúsculas e minúsculas.',
    keywords: ['buscar', 'pesquisar'],
  },
  {
    id: 'log-pickaxe',
    category: 'historico',
    title: 'Descobrir quando um trecho de código apareceu ou sumiu',
    commands: ['git log -S "calcularFrete" --oneline', 'git log -G "calcular.*Frete" --oneline'],
    explanation: 'O `-S` acha os commits que adicionaram ou removeram ocorrências do texto. O `-G` aceita uma expressão regular e acha os commits com linhas alteradas que casam com ela. Acrescente `-p` para ver as alterações.',
    keywords: ['buscar código', 'pickaxe'],
  },
  {
    id: 'log-diferenca-branches',
    category: 'historico',
    title: 'Ver commits que estão numa branch e não na outra',
    commands: ['git log --oneline main..<branch>', 'git log --oneline <branch>..main'],
    explanation: 'A notação `A..B` mostra os commits de B que não estão em A. O primeiro lista o que a sua branch tem de novo; o segundo, o que entrou na `main` e ainda não está na sua branch.',
  },
  {
    id: 'show',
    category: 'historico',
    title: 'Ver o que um commit alterou',
    commands: ['git show <hash>', 'git show --stat <hash>', 'git show'],
    explanation: 'Mostra autor, data, mensagem e o diff completo do commit. O `--stat` resume em arquivos e linhas alteradas. Sem hash, mostra o último commit (`HEAD`).',
  },
  {
    id: 'show-arquivo-antigo',
    category: 'historico',
    title: 'Ver um arquivo como ele era em outro commit',
    commands: ['git show <hash>:caminho/do/arquivo.js', 'git show main:README.md'],
    explanation: 'Imprime o conteúdo do arquivo naquela versão, sem alterar nada. O caminho é relativo à raiz do repositório. Para salvar numa cópia: `git show <hash>:caminho/do/arquivo.js > arquivo-antigo.js`.',
  },
  {
    id: 'blame',
    category: 'historico',
    title: 'Descobrir quem alterou cada linha (blame)',
    commands: ['git blame <arquivo>', 'git blame -L 10,20 <arquivo>'],
    explanation: 'Mostra, para cada linha, o commit, o autor e a data da última alteração. O `-L 10,20` limita às linhas 10 a 20. Use para entender o contexto de um trecho, não para caçar culpados.',
    keywords: ['autor', 'quem mudou'],
  },
  {
    id: 'bisect',
    category: 'historico',
    title: 'Achar o commit que introduziu um bug (bisect)',
    commands: ['git bisect start', 'git bisect bad', 'git bisect good <hash-bom>', 'git bisect reset'],
    explanation: 'Marque o commit atual como ruim (`bad`) e um commit antigo em que tudo funcionava como bom (`good`). O Git faz uma busca binária: a cada passo, teste e responda `git bisect good` ou `git bisect bad`, até ele apontar o primeiro commit ruim. O `git bisect reset` encerra e volta para onde você estava. Com um teste automatizado, `git bisect run npm test` faz tudo sozinho.',
    keywords: ['bug', 'erro', 'regressão'],
  },
  {
    id: 'reflog',
    category: 'historico',
    title: 'Ver por onde o HEAD andou (reflog)',
    commands: ['git reflog', 'git reflog show <branch>'],
    explanation: 'O reflog registra, só na sua máquina, cada movimento do HEAD: commits, trocas de branch, resets, rebases. É a rede de segurança para recuperar commits “perdidos”: ache o hash e crie uma branch nele. As entradas expiram com o tempo (por padrão, em 90 dias; em 30 para commits que ficaram inacessíveis).',
    keywords: ['recuperar', 'perdido'],
  },
  {
    id: 'grep',
    category: 'historico',
    title: 'Procurar um texto nos arquivos do repositório',
    commands: ['git grep -n "calcularFrete"', 'git grep -n "calcularFrete" <hash>'],
    explanation: 'Busca só nos arquivos rastreados (ignora `node_modules/` e afins) e mostra o número da linha com `-n`. Passando um commit, busca no código como ele era naquela versão.',
    keywords: ['buscar', 'pesquisar', 'procurar'],
  },

  // Stash
  {
    id: 'stash-guardar',
    category: 'stash',
    title: 'Guardar alterações para trocar de tarefa (stash)',
    commands: ['git stash', 'git stash push -m "formulário pela metade"'],
    explanation: 'Guarda as alterações dos arquivos rastreados (preparadas ou não) e deixa a pasta limpa, igual ao último commit. Dar um nome com `-m` ajuda a encontrar depois.',
    keywords: ['gaveta', 'temporário'],
  },
  {
    id: 'stash-novos',
    category: 'stash',
    title: 'Guardar também os arquivos novos',
    commands: ['git stash -u'],
    explanation: 'Por padrão, o stash deixa de fora os arquivos não rastreados. O `-u` (`--include-untracked`) inclui esses arquivos também.',
  },
  {
    id: 'stash-listar',
    category: 'stash',
    title: 'Ver o que está guardado no stash',
    commands: ['git stash list', 'git stash show -p stash@{0}'],
    explanation: 'O stash é uma pilha: `stash@{0}` é o item mais recente. O `git stash show -p` mostra o diff completo de um item.',
  },
  {
    id: 'stash-recuperar',
    category: 'stash',
    title: 'Recuperar as alterações guardadas',
    commands: ['git stash pop', 'git stash apply stash@{1}'],
    explanation: 'O `pop` aplica o item mais recente e o remove da pilha; o `apply` aplica e mantém uma cópia guardada. Se o `pop` der conflito, o item não é removido: resolva o conflito e depois apague-o com `git stash drop`.',
  },
  {
    id: 'stash-apagar',
    category: 'stash',
    title: 'Apagar itens do stash',
    commands: ['git stash drop stash@{1}', 'git stash clear'],
    explanation: 'O `drop` remove um item; o `clear` esvazia a pilha inteira.',
    warning: 'Itens apagados do stash são difíceis de recuperar. Confira o conteúdo com `git stash show -p` antes.',
    keywords: ['deletar', 'limpar'],
  },
  {
    id: 'stash-branch',
    category: 'stash',
    title: 'Transformar um stash em uma branch',
    commands: ['git stash branch <nova-branch> stash@{0}'],
    explanation: 'Cria uma branch a partir do commit em que o stash foi feito, aplica as alterações nela e remove o item da pilha. Ótimo quando o `pop` daria conflito porque a branch original mudou muito.',
  },
  {
    id: 'stash-arquivos',
    category: 'stash',
    title: 'Guardar só alguns arquivos',
    commands: ['git stash push -m "rascunho do rodapé" -- <arquivo1> <arquivo2>'],
    explanation: 'Só os arquivos indicados vão para o stash; o resto continua como está na sua pasta.',
  },

  // Tags e releases
  {
    id: 'tag-criar',
    category: 'tags',
    title: 'Marcar uma versão com uma tag',
    commands: ['git tag -a v1.0.0 -m "Versão 1.0.0"'],
    explanation: 'A tag anotada (`-a`) guarda autor, data e mensagem e é a recomendada para versões publicadas. Sem `-a` e `-m`, você cria uma tag leve, que é só um nome apontando para o commit. Muitos projetos seguem o versionamento semântico: MAJOR.MINOR.PATCH.',
    keywords: ['semver'],
  },
  {
    id: 'tag-listar',
    category: 'tags',
    title: 'Listar e ver tags',
    commands: ['git tag', 'git tag -l "v1.*"', 'git show v1.0.0'],
    explanation: 'Lista todas as tags, filtra por um padrão ou mostra os detalhes de uma tag e do commit para o qual ela aponta.',
  },
  {
    id: 'tag-enviar',
    category: 'tags',
    title: 'Enviar tags para o GitHub',
    commands: ['git push origin v1.0.0', 'git push origin --tags'],
    explanation: 'O `git push` comum não envia tags. Envie uma específica ou todas de uma vez. No GitHub, a partir de uma tag enviada você pode publicar uma release, com notas e arquivos para download, na página Releases.',
    keywords: ['publicar versão'],
  },
  {
    id: 'tag-commit-antigo',
    category: 'tags',
    title: 'Criar uma tag em um commit antigo',
    commands: ['git tag -a v0.9.0 <hash> -m "Versão 0.9.0"'],
    explanation: 'Basta informar o hash do commit depois do nome da tag. Encontre o hash com `git log --oneline`.',
  },
  {
    id: 'tag-apagar',
    category: 'tags',
    title: 'Apagar uma tag',
    commands: ['git tag -d v1.0.0', 'git push origin --delete v1.0.0'],
    explanation: 'O primeiro apaga a tag local; o segundo, a tag no remoto.',
    warning: 'Evite apagar ou mover tags de versões já publicadas: quem baixou a versão continua com a tag antiga e a confusão é garantida. Prefira lançar uma versão nova.',
    keywords: ['deletar', 'excluir'],
  },
  {
    id: 'tag-ver-codigo',
    category: 'tags',
    title: 'Ver o código de uma versão antiga',
    commands: ['git switch --detach v1.0.0', 'git switch -c correcao-v1 v1.0.0'],
    legacy: 'git checkout v1.0.0',
    explanation: 'O primeiro deixa você em “detached HEAD” no commit da tag, bom para olhar e testar. Para corrigir algo a partir dessa versão, crie uma branch nela, como no segundo comando.',
  },
  {
    id: 'describe',
    category: 'tags',
    title: 'Descobrir de qual versão um commit está mais perto',
    commands: ['git describe --tags'],
    explanation: 'Mostra a tag mais recente alcançável a partir do commit atual. Uma saída como `v1.2.0-3-gabc1234` significa: 3 commits depois da `v1.2.0`, no commit `abc1234`.',
  },

  // Conflitos
  {
    id: 'conflito-entender',
    category: 'conflitos',
    title: 'Entender as marcações de conflito',
    commands: ['git status'],
    explanation: 'Quando duas alterações mexem na mesma região, o Git marca o arquivo como “both modified” e insere no texto: `<<<<<<<` (início da versão da sua branch), `=======` (separador) e `>>>>>>>` (fim da versão que está chegando). Você decide o resultado final, apaga as marcações e salva.',
    keywords: ['conflict', 'both modified'],
  },
  {
    id: 'conflito-resolver-merge',
    category: 'conflitos',
    title: 'Resolver um conflito de merge',
    commands: ['git status', 'git add <arquivo>', 'git commit'],
    explanation: 'Abra cada arquivo em conflito e edite até ficar do jeito certo, sem as marcações `<<<<<<<`, `=======` e `>>>>>>>`. Marque como resolvido com `git add` e finalize com `git commit`; a mensagem de merge já vem pronta. O `git merge --continue` também finaliza.',
  },
  {
    id: 'conflito-abortar',
    category: 'conflitos',
    title: 'Desistir do merge e voltar como estava',
    commands: ['git merge --abort'],
    explanation: 'Cancela o merge em andamento e restaura o estado anterior. Também serve para conflitos vindos de um `git pull` que faz merge. Dica: evite começar um merge com alterações não commitadas, porque nesse caso nem sempre dá para restaurá-las.',
    keywords: ['cancelar merge'],
  },
  {
    id: 'conflito-escolher-lado',
    category: 'conflitos',
    title: 'Ficar com uma das versões inteira',
    commands: ['git restore --ours <arquivo>', 'git restore --theirs <arquivo>', 'git add <arquivo>'],
    legacy: 'git checkout --ours <arquivo>',
    explanation: 'Num merge, `--ours` é a versão da sua branch atual e `--theirs` é a da branch que está chegando. Depois de escolher, marque como resolvido com `git add`.',
    warning: 'Durante um rebase, os papéis se invertem: `--ours` é a branch de destino (por exemplo, a `main`) e `--theirs` são os seus commits sendo reaplicados.',
    keywords: ['ours', 'theirs', 'minha versão'],
  },
  {
    id: 'conflito-rebase',
    category: 'conflitos',
    title: 'Resolver conflitos durante um rebase',
    commands: ['git add <arquivo>', 'git rebase --continue', 'git rebase --skip', 'git rebase --abort'],
    explanation: 'O rebase para em cada commit com conflito. Resolva os arquivos, marque com `git add` e siga com `--continue`. O `--skip` descarta o commit atual (cuidado) e o `--abort` cancela tudo, voltando ao estado de antes do rebase.',
  },
  {
    id: 'conflito-listar',
    category: 'conflitos',
    title: 'Listar só os arquivos em conflito',
    commands: ['git diff --name-only --diff-filter=U'],
    explanation: 'O filtro `U` (unmerged) mostra só os arquivos que ainda têm conflito não resolvido. Útil quando o `git status` está muito poluído.',
  },
  {
    id: 'conflito-zdiff3',
    category: 'conflitos',
    title: 'Ver também a versão original dentro do conflito',
    commands: ['git config --global merge.conflictStyle zdiff3'],
    explanation: 'Além das duas versões em disputa, o Git passa a mostrar, entre `|||||||` e `=======`, como o trecho era antes das duas alterações. Isso ajuda muito a entender o que cada lado mudou. O `zdiff3` existe desde o Git 2.35; em versões antigas, use `diff3`.',
  },
  {
    id: 'conflito-mergetool',
    category: 'conflitos',
    title: 'Resolver conflitos numa ferramenta visual',
    commands: [
      'git config --global merge.tool code',
      "git config --global mergetool.code.cmd 'code --wait --merge $REMOTE $LOCAL $BASE $MERGED'",
      'git mergetool',
    ],
    explanation: 'As duas configurações usam o editor de merge do VS Code; depois disso, o `git mergetool` abre nele cada arquivo em conflito, um por vez.',
    keywords: ['vscode', 'visual'],
  },
  {
    id: 'rerere',
    category: 'conflitos',
    title: 'Fazer o Git lembrar como você resolveu um conflito',
    commands: ['git config --global rerere.enabled true'],
    explanation: 'Com o rerere (“reuse recorded resolution”), o Git grava cada resolução de conflito e a reaplica sozinho se o mesmo conflito aparecer de novo, o que é comum em rebases repetidos de branches longas.',
  },

  // .gitignore
  {
    id: 'gitignore-basico',
    category: 'gitignore',
    file: '.gitignore',
    title: 'Ignorar arquivos com o .gitignore',
    commands: ['node_modules/', '*.log', '.env', '/dist', '!importante.log'],
    explanation: 'Crie um arquivo `.gitignore` na raiz do projeto, com um padrão por linha. Barra no fim (`node_modules/`) vale só para pastas; `*` é curinga; barra no começo (`/dist`) vale só na raiz; `!` cria uma exceção; linhas começando com `#` são comentários. Commite o `.gitignore` junto com o projeto.',
  },
  {
    id: 'gitignore-ja-rastreado',
    category: 'gitignore',
    title: 'Parar de versionar um arquivo que já foi commitado',
    commands: ['git rm --cached <arquivo>', 'git rm -r --cached <pasta>', 'git commit -m "Para de versionar a configuração local"'],
    explanation: 'O `.gitignore` só vale para arquivos que o Git ainda não rastreia. Para um arquivo já commitado, coloque-o no `.gitignore` e tire-o do índice com `--cached`, que mantém a sua cópia local.',
    warning: 'Quando os colegas fizerem pull desse commit, o arquivo será apagado da pasta deles: avise antes. E se ele tinha senhas, elas continuam no histórico, então troque-as.',
    keywords: ['untrack', 'parar de rastrear'],
  },
  {
    id: 'gitignore-global',
    category: 'gitignore',
    title: 'Ignorar arquivos em todos os seus repositórios',
    commands: ['git config --global core.excludesFile ~/.gitignore_global', 'echo ".DS_Store" >> ~/.gitignore_global'],
    explanation: 'Ideal para arquivos do seu sistema ou editor (`.DS_Store`, `Thumbs.db`, `.idea/`), que não fazem sentido no `.gitignore` de cada projeto.',
  },
  {
    id: 'gitignore-verificar',
    category: 'gitignore',
    title: 'Descobrir por que um arquivo está sendo ignorado',
    commands: ['git check-ignore -v <arquivo>'],
    explanation: 'Mostra qual arquivo de regras e qual linha fazem o Git ignorar aquele caminho. Se não aparecer nada, o arquivo não está sendo ignorado.',
  },
  {
    id: 'gitignore-local',
    category: 'gitignore',
    title: 'Ignorar algo só na sua máquina',
    commands: ['echo "anotacoes.txt" >> .git/info/exclude'],
    explanation: 'O arquivo `.git/info/exclude` usa a mesma sintaxe do `.gitignore`, mas não é versionado: vale só para o seu clone.',
  },
  {
    id: 'gitignore-ver-ignorados',
    category: 'gitignore',
    title: 'Ver quais arquivos estão sendo ignorados',
    commands: ['git status --ignored'],
    explanation: 'Acrescenta à saída do status uma seção com os arquivos e pastas ignorados.',
  },
  {
    id: 'gitignore-pasta-vazia',
    category: 'gitignore',
    title: 'Versionar uma pasta vazia',
    commands: ['touch uploads/.gitkeep', 'git add uploads/.gitkeep'],
    explanation: 'O Git não rastreia pastas, só arquivos. A convenção é criar dentro da pasta um arquivo vazio chamado `.gitkeep`: o nome não tem nada de especial, é só um costume.',
  },
  {
    id: 'gitignore-excecao-pasta',
    category: 'gitignore',
    file: '.gitignore',
    title: 'Ignorar o conteúdo de uma pasta, menos um arquivo',
    commands: ['uploads/*', '!uploads/.gitkeep'],
    explanation: 'Use `uploads/*` (o conteúdo) e não `uploads/` (a pasta inteira): quando a pasta em si é ignorada, o Git nem olha dentro dela e a exceção com `!` não funciona.',
  },

  // Socorro!
  {
    id: 'socorro-commit-na-main',
    category: 'socorro',
    title: 'Commitei na main, mas era para ser numa branch nova',
    commands: ['git branch <nova-branch>', 'git reset --hard HEAD~1', 'git switch <nova-branch>'],
    explanation: 'A branch nova é criada apontando para o seu commit; depois a `main` volta um commit (use `HEAD~2`, `HEAD~3` e assim por diante se foram mais) e você segue o trabalho na branch nova. Funciona se os commits ainda não foram enviados.',
    warning: 'O `reset --hard` descarta alterações não commitadas: faça commit ou `git stash` antes.',
    keywords: ['branch errada', 'commit errado'],
  },
  {
    id: 'socorro-branch-errada',
    category: 'socorro',
    title: 'Commitei na branch errada (e a certa já existe)',
    commands: ['git log --oneline -1', 'git switch <branch-certa>', 'git cherry-pick <hash>', 'git switch <branch-errada>', 'git reset --hard HEAD~1'],
    explanation: 'Anote o hash do commit (primeiro comando), copie-o para a branch certa com `cherry-pick` e depois remova-o da branch errada. Se a branch errada já foi enviada, em vez do reset use `git revert <hash>` nela.',
    warning: 'Confira se não há alterações não commitadas antes do `reset --hard`: elas seriam perdidas.',
    keywords: ['commit errado'],
  },
  {
    id: 'socorro-desfazer-commit',
    category: 'socorro',
    title: 'Quero desfazer o último commit sem perder as alterações',
    commands: ['git reset --soft HEAD~1', 'git reset HEAD~1'],
    explanation: 'Com `--soft`, as alterações voltam para o staging, prontas para outro commit; sem ele (modo `--mixed`), voltam só para os arquivos. Se o commit já foi enviado e outras pessoas podem tê-lo baixado, use `git revert HEAD`.',
    keywords: ['uncommit'],
  },
  {
    id: 'socorro-branch-apagada',
    category: 'socorro',
    title: 'Apaguei uma branch sem querer',
    commands: ['git reflog', 'git branch <nome-da-branch> <hash>'],
    explanation: 'Se você acabou de apagar, o próprio `git branch -D` mostrou o hash na mensagem: “Deleted branch nome (was abc1234)”. Senão, procure no `git reflog` o último commit em que você estava na branch, por exemplo a entrada logo abaixo de “checkout: moving from <nome-da-branch> to main”. Depois, recrie a branch apontando para esse hash.',
    keywords: ['recuperar branch', 'deletei', 'excluí'],
  },
  {
    id: 'socorro-segredo-enviado',
    category: 'socorro',
    title: 'Enviei uma senha ou um token para o GitHub',
    commands: [
      'git filter-repo --invert-paths --path <arquivo-com-segredo>',
      'git filter-repo --replace-text segredos.txt',
      'git remote add origin <url>',
      'git push origin --force --all',
      'git push origin --force --tags',
    ],
    explanation: 'Primeiro, e mais importante: revogue ou troque o segredo agora mesmo, no serviço de onde ele veio. Considere que ele já vazou, porque robôs varrem o GitHub o tempo todo. Depois, limpe o histórico com o git filter-repo (ferramenta à parte: `pip install git-filter-repo` ou `brew install git-filter-repo`), num clone novo do repositório. O primeiro comando apaga o arquivo de todo o histórico; o segundo, em vez disso, troca cada texto listado em `segredos.txt` (um por linha) por `***REMOVED***` em todos os commits. O filter-repo remove o remoto `origin` por segurança: adicione-o de novo e envie tudo.',
    warning: 'O push forçado reescreve o histórico de todo mundo: combine com o time antes, peça que ninguém envie nada durante a limpeza e, depois, que todos clonem o repositório de novo (clones antigos ainda têm o segredo e podem trazê-lo de volta). Forks e cópias que já existiam continuam com o segredo; por isso, revogar é o passo que realmente protege você.',
    keywords: ['senha', 'token', 'segredo', 'credencial', 'chave', 'vazou', 'api key', '.env'],
  },
  {
    id: 'socorro-segredo-local',
    category: 'socorro',
    title: 'Commitei uma senha, mas ainda não enviei',
    commands: ['git rm --cached .env', 'echo ".env" >> .gitignore', 'git add .gitignore', 'git commit --amend --no-edit'],
    explanation: 'Se o segredo só está no último commit local, corrija esse commit antes do push. O exemplo tira o `.env` do commit (mantendo o arquivo na sua máquina) e passa a ignorá-lo. Se o segredo estava dentro de um arquivo que deve continuar versionado, apague-o do arquivo, rode `git add` e faça o `--amend`. Se ele está em commits mais antigos, use o rebase interativo.',
    keywords: ['senha', 'token', 'segredo', '.env'],
  },
  {
    id: 'socorro-detached-head',
    category: 'socorro',
    title: 'O Git diz que estou em “detached HEAD”',
    commands: ['git switch -c <nova-branch>', 'git switch main'],
    explanation: 'Você está num commit específico (por exemplo, depois de abrir uma tag ou um hash), fora de qualquer branch. Para só olhar, tudo bem; para voltar, use `git switch main`. Se fez commits aí e quer mantê-los, crie uma branch antes de sair, com o primeiro comando. Se já saiu, o Git mostrou o hash na mensagem; ele também aparece no `git reflog`.',
    keywords: ['head desanexado', 'detached'],
  },
  {
    id: 'socorro-pull-conflito',
    category: 'socorro',
    title: 'O git pull deu conflito',
    commands: ['git status', 'git add <arquivo>', 'git commit', 'git merge --abort'],
    explanation: 'O `git status` lista os arquivos em conflito. Resolva cada um (veja a seção Conflitos), marque com `git add` e conclua com `git commit`, ou com `git rebase --continue` se o seu pull usa rebase. Para desistir e voltar a como estava antes do pull, use `git merge --abort` (ou `git rebase --abort`).',
  },
  {
    id: 'socorro-push-rejeitado',
    category: 'socorro',
    title: 'O push foi rejeitado (rejected, non-fast-forward)',
    commands: ['git pull --rebase', 'git push'],
    explanation: 'O remoto tem commits que você ainda não tem: alguém enviou antes. Traga essas novidades com `git pull --rebase` (ou `git pull`), resolva os conflitos, se houver, e envie de novo.',
    warning: 'Não use `git push --force` para “resolver” isso: você apagaria os commits da outra pessoa.',
    keywords: ['fetch first', 'recusado'],
  },
  {
    id: 'socorro-reset-errado',
    category: 'socorro',
    title: 'Dei reset --hard e perdi commits',
    commands: ['git reflog', 'git reset --hard HEAD@{1}'],
    explanation: 'O reflog lista as posições anteriores do HEAD; `HEAD@{1}` é onde você estava antes do último movimento. Confira no reflog qual entrada quer recuperar antes de rodar o comando. Alterações que nunca foram commitadas não aparecem lá.',
    warning: 'Este `reset --hard` também descarta as alterações não commitadas que existirem agora.',
    keywords: ['recuperar', 'perdi', 'sumiu'],
  },
  {
    id: 'socorro-merge-errado',
    category: 'socorro',
    title: 'Fiz merge da branch errada (e ainda não enviei)',
    commands: ['git reset --merge ORIG_HEAD'],
    explanation: 'Depois de um merge, o Git guarda em `ORIG_HEAD` onde a branch estava antes. Esse comando volta para lá e preserva alterações locais que não tinham relação com o merge. Se o merge já foi enviado, use `git revert -m 1 <hash-do-merge>`.',
    keywords: ['desfazer merge'],
  },
  {
    id: 'socorro-arquivo-grande',
    category: 'socorro',
    title: 'O GitHub recusou o push por causa de um arquivo grande',
    commands: ['git rm --cached <arquivo-grande>', 'git commit --amend --no-edit', 'git push'],
    explanation: 'O GitHub bloqueia arquivos com mais de 100 MB. Se o arquivo entrou no último commit, tire-o com `--cached` (ele continua na sua pasta), coloque-o no `.gitignore` e refaça o commit. Se ele entrou em commits mais antigos, use o rebase interativo ou o `git filter-repo`. Para versionar arquivos grandes de propósito, use o Git LFS.',
    keywords: ['large file', 'lfs', 'tamanho'],
  },
  {
    id: 'socorro-mensagem-antiga',
    category: 'socorro',
    title: 'Errei a mensagem de um commit antigo',
    commands: ['git rebase -i HEAD~5'],
    explanation: 'No editor, troque `pick` por `reword` na linha do commit, salve e feche; o Git abre a mensagem para você corrigir. Ajuste o número até alcançar o commit desejado.',
    warning: 'Reescreve aquele commit e todos os seguintes. Se já foram enviados, você vai precisar de `git push --force-with-lease` e de combinar com o time.',
  },
];
